### PR TITLE
Add "CFBundleShortVersionString" plist key

### PR DESCRIPTION
**Pull request by piksel**
I noticed that the "CFBundleShortVersionString" didn't get added to the Info.plist file, so I added it

### CODE REVIEW

**Comment by x2bool** [comment]
Thank you!

**Comment by piksel** [comment]
I noted that [create-dmg](https://github.com/andreyvit/create-dmg) named the output dmg's "AppName undefined.dmg", and this was why.

**Comment by x2bool** [comment]
BTW What is your use case? Some Avalonia project?

**Comment by piksel** [comment]
Yep! It's currently private, but I plan to make it public with the 1.0 release.

**Pull request merged**
